version: '3.8'

networks:
    laravel_network:
        name: laravel_network

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.local
        container_name: laravel_web
        networks:
            - laravel_network
        restart: always
        links:
            - postgres
            - redis
        depends_on:
            - postgres
            - redis
        volumes:
            - ./:/var/www/html
        ports:
            - "127.0.0.1:9980:80"

    postgres:
        image: postgres:16.3
        container_name: laravel_postgres
        networks:
            - laravel_network
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./docker/data/postgres-storage/:/var/lib/postgresql/data

    redis:
        image: redis:7.2
        container_name: laravel_redis
        networks:
            - laravel_network
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        restart: always
        volumes:
            - ./docker/data/redis-storage/:/data
        ports:
            - "127.0.0.1:9979:6379"

    pgadmin:
        image: dpage/pgadmin4
        container_name: laravel_pgadmin
        networks:
            - laravel_network
        links:
            - postgres
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL_ADDRESS}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        volumes:
            - ./docker/data/pgadmin-storage/:/var/lib/pgadmin
        restart: on-failure
        ports:
            - "127.0.0.1:9901:80"
