[program:pulse]
command=php /var/www/html/artisan pulse:work
autostart=true
autorestart=true
stdout_logfile=/var/log/laravel_pulse_redis.log
stderr_logfile=/var/log/laravel_pulse_redis_error.log
user=www-data
